export const vehicleData = [
  {
    index: 1,
    vehicleId: 132456,
    type: "Scooter",
    locked: "Locked",
    speed: "0 km/h",
    battery: "100%",
    status: "PARKING",
    location: 3.142012,
    lastUpdated: "2019-07-02 9:00AM",
  },
  {
    index: 2,
    vehicleId: 987654,
    type: "Scooter",
    locked: "Unlocked",
    speed: "5 km/h",
    battery: "75%",
    status: "MOVING",
    location: 2.125114,
    lastUpdated: "2019-07-02 10:00AM",
  },
  {
    index: 3,
    vehicleId: 569825,
    type: "Scooter",
    locked: "Unlocked",
    speed: "0 km/h",
    battery: "50%",
    status: "IDLING",
    location: 4.125114,
    lastUpdated: "2019-07-02 10:00AM",
  },
  {
    index: 4,
    vehicleId: 125864,
    type: "Scooter",
    locked: "Locked",
    speed: "0 km/h",
    battery: "15%",
    status: "TOWING",
    location: 5.125114,
    lastUpdated: "2019-07-02 10:00AM",
  },
  {
    index: 5,
    vehicleId: 125864,
    type: "Scooter",
    locked: "Locked",
    speed: "0 km/h",
    battery: "0%",
    status: "TOWING",
    location: 5.125114,
    lastUpdated: "2019-07-02 10:00AM",
  },
];

export const columns = [
  {
    title: "Vehicle ID",
    dataIndex: "vehicleId",
    key: "vehicleId",
    sorter: (a, b) => parseInt(a.vehicleId) - parseInt(b.vehicleId),
  },
  {
    title: "Type",
    dataIndex: "type",
    key: "type",
    sorter: (a, b) => a.type.localeCompare(b.type),
  },
  {
    title: "Locked / Unlocked",
    dataIndex: "locked",
    key: "locked",
    sorter: (a, b) => a.locked.localeCompare(b.locked),
  },
  {
    title: "Speed",
    dataIndex: "speed",
    key: "speed",
    sorter: (a, b) => parseInt(a.speed) - parseInt(b.speed),
  },
  {
    title: "Battery",
    dataIndex: "battery",
    key: "battery",
    sorter: (a, b) => parseInt(a.battery) - parseInt(b.battery),
  },
  {
    title: "Status",
    dataIndex: "status",
    key: "status",
    sorter: (a, b) => a.status.localeCompare(b.status),
  },
  {
    title: "Location",
    dataIndex: "location",
    key: "location",
    sorter: (a, b) => parseInt(a.location) - parseInt(b.location),
  },
  {
    title: "Last Updated",
    dataIndex: "lastUpdated",
    key: "lastUpdated",
    sorter: (a, b) => new Date(a.date) - new Date(b.date),
  },
];
